version: '3.8'

services:
  aws-mcp-server:
    build: .
    container_name: aws-mcp-server
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - MCP_SERVER_PORT=8000
      - FASTMCP_LOG_LEVEL=INFO
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/sse"]
      interval: 30s
      timeout: 10s
      retries: 3 