# Cloudflare Workers Configuration - TypeScript MCP Server
# Based on: https://developers.cloudflare.com/workers/configuration/

name = "aws-docs-mcp-server"
main = "src/index.ts"
compatibility_date = "2024-11-05"
compatibility_flags = ["nodejs_compat"]

# Optional: Uncomment for custom domains
# routes = [
#   { pattern = "mcp.yourdomain.com/*", zone_name = "yourdomain.com" }
# ] 